# -*- coding: utf-8 -*-
"""star_all.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/ayushved78/6bcb9c47db89a3dc186d0930773bb97f/star_all.ipynb

#LOWER STAR PATTERN
"""

n = int(input("value of n: "))
for i in range(0,n):
  for j in range(0,i+1):
    print("* ",end=" ")
  print("\r")

"""# RIGHT LOWER PATTERN"""

n = int(input("value of n: "))
k=2*n-2
for i in range(0,n):
  for j in range(0,k):
    print(end=" ")
  k=k-2
  for j in range(0,i+1):
    print("* ",end="")
  print("\r")

"""# DOWN LEFT PATTERN

"""

n = int(input("value of n: "))
for i in range(n,-1,-1):
  for j in range(0,i+1):
    print("* ",end=" ")
  print("\r")

"""#DIAMOND STAR PATTERN"""

n = int(input("value of n: "))
for i in range(n):
  for j in range(n):
    if i+j==2 or i-j==2 or i+j==6 or j-i==2:
      print("* ",end="")
    else:
      print(end=" ")
  print("\r")

"""#HOUR GLASS PATTERN"""

n = int(input("value of n: "))
k=n-2
for i in range(n,-1,-1):
  for j in range(k,0,-1):
    print(end=" ")
  k=k+1
  for j in range(0,i+1):
    print("* ",end="")
  print("\r")
k=2*n-2
for i in range(0,n+1):
  for j in range(0,k):
    print(end=" ")
  k=k-1
  for j in range(0,i+1):
    print("* ",end="")
  print("\r")

